ext {
    extName = 'Nekopoi'
    extClass = '.Nekopoi'
    extVersionCode = 2
    isNsfw = true
}

apply plugin: "kei.plugins.extension.legacy"

dependencies {
    implementation(project(":lib:doodextractor"))
    implementation(project(":lib:streamwishextractor"))
    implementation(project(":lib:vidhideextractor"))
}
